/**
 * Galería generada desde public/Salvador y Chely
 * Ejecutar: node scripts/generate-gallery-items.mjs
 */

import type { GalleryItem } from "./site";

export const galleryItems: GalleryItem[] = [
  { src: "/Salvador y Chely/Chely embarazada.jpeg", caption: "Esperando con el corazón lleno" },
  { src: "/Salvador y Chely/chely embarazada exhibiendo su panza.jpeg", caption: "Tu panza, nuestro mundo" },
  { src: "/Salvador y Chely/chely embarazada luciendo su panza rodeada de plantas.jpeg", caption: "Vida nueva entre plantas" },
  { src: "/Salvador y Chely/chely embarazada con braga amarilla.jpeg", caption: "Brillo de embarazo" },
  { src: "/Salvador y Chely/chely embarazada exhbiendo barriga pintada con una bomba como broma.jpeg", caption: "Humor de mamá" },
  { src: "/Salvador y Chely/chey embarazada en ropa vinotinto.jpeg", caption: "Color vinotinto y promesa" },
  { src: "/Salvador y Chely/foto de la barriga embarazada de chely con osito de peluche al lado.jpeg", caption: "Osito esperando a Salvador" },
  { src: "/Salvador y Chely/Chely y Salva esperando su cita en el ginecologo.jpeg", caption: "Salvador con dos meses: nervios y magia" },
  { src: "/Salvador y Chely/foto de chely agarrando la mano de u esposo justo cuando esta dando a luz.jpeg", caption: "El momento en que todo cambia" },
  { src: "/Salvador y Chely/Nacimiento Salva.jpeg", caption: "El día que llegaste" },
  { src: "/Salvador y Chely/salvador en la incubadora con minutos de nacido.jpeg", caption: "Primeros minutos de vida" },
  { src: "/Salvador y Chely/mano de recien nacido de salvador.jpeg", caption: "Manito diminuta" },
  { src: "/Salvador y Chely/salvador recien nacido.jpeg", caption: "Recién nacido, todo por descubrir" },
  { src: "/Salvador y Chely/salvador recien nacido 2.jpeg", caption: "Tan pequeño, tan grande" },
  { src: "/Salvador y Chely/salvador recien nacido 3.jpeg", caption: "Primer suspiros" },
  { src: "/Salvador y Chely/salvador recien nacido 4.jpeg", caption: "Mirada nueva" },
  { src: "/Salvador y Chely/Salvador con su foto mas hermosa de recien nacido, durmiendo, 3 dias de nacido.jpeg", caption: "Tres días de sueño celestial" },
  { src: "/Salvador y Chely/Chely dandole teta a salvador en la clinica mientras la doctora le explica como hacerlo.jpeg", caption: "Primeras lecciones de mamá" },
  { src: "/Salvador y Chely/la primera vez de chely alimentando con teta a salvador.jpeg", caption: "La primera vez que te alimentó" },
  { src: "/Salvador y Chely/chely en la cama de la clinica y salvador en su camita de clinica uno al lado del otro.jpeg", caption: "Lado a lado en la clínica" },
  { src: "/Salvador y Chely/Chely cargando a salva con su bata de clinica en el ultimo dia en cla clinica antes del alta.jpeg", caption: "Último día en la clínica" },
  { src: "/Salvador y Chely/salva en su asiento del carro saliendo de la clinica por primera vez.jpeg", caption: "Primera salida: rumbo a casa" },
  { src: "/Salvador y Chely/salvador bebe tomando teta.jpeg", caption: "Calma y leche" },
  { src: "/Salvador y Chely/salvador amamantandose.jpeg", caption: "Todo lo que necesitas" },
  { src: "/Salvador y Chely/salvador bebe en el pecho de chely dormidito.jpeg", caption: "Dormido en el mejor lugar" },
  { src: "/Salvador y Chely/salvador bebe con la mano como pensativo viendo la teta de chely.jpeg", caption: "Pequeño filósofo" },
  { src: "/Salvador y Chely/chely y salva tomando tete.jpeg", caption: "Tete con calma" },
  { src: "/Salvador y Chely/Salva chely y maximo en la cama salva tomando teta.jpeg", caption: "Familia en la cama" },
  { src: "/Salvador y Chely/close up de manos de salvador agarrando el dedo de chely muy tierna.jpeg", caption: "Tu dedo, su refugio" },
  { src: "/Salvador y Chely/close up de salva bebe durmiendo.jpeg", caption: "Sueño profundo" },
  { src: "/Salvador y Chely/close up de salva con chupon.jpeg", caption: "Chupón y paz" },
  { src: "/Salvador y Chely/salva bebe durmiendo.jpeg", caption: "Ángel dormido" },
  { src: "/Salvador y Chely/salva bebecito de 1 mes con ropa y sueter .jpeg", caption: "Un mes de estilo" },
  { src: "/Salvador y Chely/salva de semana close up viendo la camara.jpeg", caption: "Ya mirando a la cámara" },
  { src: "/Salvador y Chely/salva de semanas tomanto teta.jpeg", caption: "Semanas de ternura" },
  { src: "/Salvador y Chely/foto de salva de menos de 1 mes, levantando la cabeza por primera vez.jpeg", caption: "Primera vez que levantó la cabeza" },
  { src: "/Salvador y Chely/foto profesional de salvador celebrando sus 2 meses, tomada por chely.jpeg", caption: "Dos meses: retrato de mamá" },
  { src: "/Salvador y Chely/foto artistica de salvador celbrando su primer mes, hecha por chely.jpeg", caption: "Un mes: foto artística" },
  { src: "/Salvador y Chely/salvador de 2 meses serio viendo la camara.jpeg", caption: "Seriedad de modelo" },
  { src: "/Salvador y Chely/Salvador de 2 meses vestido elegante, dormido.jpeg", caption: "Elegancia dormida" },
  { src: "/Salvador y Chely/Salvador de 1 mes con chely cargandolo en su primera invitacion a un cumpleaños.jpeg", caption: "Primera fiesta de cumpleaños" },
  { src: "/Salvador y Chely/Salvador de menos de 1 mes escuchando a Luis miguel.jpeg", caption: "Fan de Luis Miguel desde la cuna" },
  { src: "/Salvador y Chely/salvador flaquito y de semanas con la ropa del real madrid.jpeg", caption: "Del Madrid desde pequeño" },
  { src: "/Salvador y Chely/Salvador en su coche de bebe viendo a la camara.jpeg", caption: "En su trono con ruedas" },
  { src: "/Salvador y Chely/foto de chely acostada en el sofa con salva durmiendo en su pecho, ella esta agotada pero cumpliendo con su rol de madre.jpeg", caption: "Agotada y feliz: mamá" },
  { src: "/Salvador y Chely/salva encima de chely durmiendo en la cama.jpeg", caption: "Durmieron así" },
  { src: "/Salvador y Chely/chely cargando a salvador para qu duerma.jpeg", caption: "En brazos hasta dormir" },
  { src: "/Salvador y Chely/Chely y salva bebe acostado en el pecho de chely chely con cara de agotada.jpeg", caption: "Agotamiento hermoso" },
  { src: "/Salvador y Chely/chely y salva durmiendo chupand dedo.jpeg", caption: "Dedo y sueño" },
  { src: "/Salvador y Chely/salva y chely acostados salva con la pierna encima de chely, solo se ven las piernas de ambos.jpeg", caption: "Piernas entrelazadas" },
  { src: "/Salvador y Chely/foto comica de chely cargando a salvador que se hizo popo y se ve la popo.jpeg", caption: "Momento cómico real" },
  { src: "/Salvador y Chely/Chely y salva foto comica.jpeg", caption: "Risas garantizadas" },
  { src: "/Salvador y Chely/Salva equipado para la guerra (de juguetes).jpeg", caption: "Listo para la batalla de juguetes" },
  { src: "/Salvador y Chely/salva riendo con capucha como el chavo del 8.jpeg", caption: "Risas estilo Chavo" },
  { src: "/Salvador y Chely/Salva riendo con gorra.jpeg", caption: "Con gorra y sonrisa" },
  { src: "/Salvador y Chely/Salva riendo con sombrero.jpeg", caption: "Sombrero y carcajada" },
  { src: "/Salvador y Chely/Salva riendo coqueto.jpeg", caption: "Coqueto y feliz" },
  { src: "/Salvador y Chely/Chely y salva close up mejilla con mejilla riendo a la camara.jpeg", caption: "Mejilla con mejilla" },
  { src: "/Salvador y Chely/Chely y salva sonriendo.jpeg", caption: "Sonrisas juntas" },
  { src: "/Salvador y Chely/chely besando a salva en la mejilla.jpeg", caption: "Beso en la mejilla" },
  { src: "/Salvador y Chely/chely besando a salvador en el malecon, salva con los ojos cerrados.jpeg", caption: "Beso en el malecón" },
  { src: "/Salvador y Chely/Chely cargando a salva en el malecon con el mar de fondo.jpeg", caption: "Mar de fondo, amor de frente" },
  { src: "/Salvador y Chely/chely y salva closeup con el sol iluminandolos.jpeg", caption: "Sol en la piel" },
  { src: "/Salvador y Chely/Ojos de chely y salva.jpeg", caption: "Los mismos ojos" },
  { src: "/Salvador y Chely/chely y salva abrazados .jpeg", caption: "Abrazo que lo dice todo" },
  { src: "/Salvador y Chely/chely y salva en el ascensor 2.jpeg", caption: "Ascensor, segunda toma" },
  { src: "/Salvador y Chely/Chely y salva foto en el ascensor riendo.jpeg", caption: "Risas en el ascensor" },
  { src: "/Salvador y Chely/chely y salva en el carro.jpeg", caption: "Viaje en carro" },
  { src: "/Salvador y Chely/salva con su abuela y chely en retaurante tanta, su primera salida a restaurant.jpeg", caption: "Primera vez en restaurante" },
  { src: "/Salvador y Chely/Chely y salva en un cumpleaños.jpeg", caption: "Cumpleaños en familia" },
  { src: "/Salvador y Chely/Hermosa foto de chely y salva en un cumpleaños.jpeg", caption: "Otro cumple, otra joya" },
  { src: "/Salvador y Chely/chely y salva en navidad vestidos con la misma pijama.jpeg", caption: "Navidad en pijama a juego" },
  { src: "/Salvador y Chely/Salva y chely en el parque en un picnic.jpeg", caption: "Picnic en el parque" },
  { src: "/Salvador y Chely/Chely y salvador foto epica en sombras.jpeg", caption: "Sombras de película" },
  { src: "/Salvador y Chely/Salvador volando en los brazos de chely.jpeg", caption: "Volando en tus brazos" },
  { src: "/Salvador y Chely/salvador volando en los brazos de chely 2.jpeg", caption: "Vuelo número dos" },
  { src: "/Salvador y Chely/Laika (nuestra perra) con salvador en la cama protegiendolo durmiendo.jpeg", caption: "Laika guardián" },
  { src: "/Salvador y Chely/laika protegiendo a salvador mientras duermen ambos (laika es nuestra perra).jpeg", caption: "Laika de guardia" },
  { src: "/Salvador y Chely/maximo (nuestro perro) chely y salvador acostados en el sofa, salva durmiendo en el pecho de chely.jpeg", caption: "Máximo y la siesta familiar" },
  { src: "/Salvador y Chely/selfie chely y salvador 2.jpeg", caption: "Selfie familiar" },
  { src: "/Salvador y Chely/selfie de chely con salvador con capucha.jpeg", caption: "Selfie con capucha" },
  { src: "/Salvador y Chely/selfie salva y chely bistezando ambos.jpeg", caption: "Ambos bizteando" },
  { src: "/Salvador y Chely/Chely y Slava tomando biberon sonriendo.jpeg", caption: "Biberón y sonrisa" },
];
